version: '3'

networks:
  default:
    name: proxy

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./extra.conf:/etc/nginx/conf.d/extra.conf
    container_name: proxy